# Following are the minimum set of parameters required to create a Google Cloud Run Service.
# Please make sure your uploaded manifest file includes all of them.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nexapay-api
  annotations:
    run.googleapis.com/invoker-iam-disabled: 'true'
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/prj-wallacefigueiredo-91659d/k8s-wallacefigueiredo/api:latest
          ports:
            - containerPort: 8080
          startupProbe:
           tcpSocket:
             port: 8080
           initialDelaySeconds: 5
           timeoutSeconds: 5
           failureThreshold: 10
           periodSeconds: 5
