{{- if .Values.dockerconfigjson}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-dockercfg
  labels:
    app: {{.Values.name}}
type: kubernetes.io/dockerconfigjson
data:
  # Harness injects the registry credential from the artifact's connector.
  .dockerconfigjson: {{.Values.dockerconfigjson}}
{{- end}}
