apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-service
  labels:
    app: {{.Values.name}}
spec:
  type: {{.Values.service.type}}
  selector:
    app: {{.Values.name}}
  ports:
    - name: http
      protocol: TCP
      port: {{int .Values.service.port}}
      targetPort: {{int .Values.service.targetPort}}
